package com.dealflow.backend.audit;

public enum AuditEventType {
    DEAL_CREATED,
    DEAL_UPDATED,
    DEAL_SUBMITTED,
    DEAL_RESUBMITTED,
    DEAL_WORKFLOW_TRANSITION,
    APPROVAL_CREATED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    APPROVAL_CHANGES_REQUESTED,
    APPROVAL_SUPERSEDED,
    EXCEPTION_CREATED,
    EXCEPTION_APPROVED,
    EXCEPTION_REJECTED,
    EXCEPTION_SUPERSEDED
}
