spring.application.name=backend
server.port=${SERVER_PORT:8081}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://127.0.0.1:5433/dealflow}
spring.datasource.username=${DATABASE_USERNAME:user}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false